{
    'name': 'Freemoov Livechat AI',
    'version': '17.0.0.1.0',
    'category': 'Website/Live Chat',
    'summary': 'Hybrid livechat bot: Odoo native chatbot + Claude fallback on open questions',
    'author': 'Freemoov',
    'website': 'https://freemoov.com',
    'depends': ['im_livechat', 'product', 'website_sale', 'website_freemoov', 'project', 'sms'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_config_parameter_data.xml',
        'data/res_partner_data.xml',
        'views/res_config_settings_view.xml',
        'views/livechat_ai_log_view.xml',
        'views/verification_view.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
